config/routes.rb
Campusevents::Application.routes.draw do
  resources :attendees

  resources :meetings

  resources :locations

  resources :sponsors

  resources :events

  root 'events#index'

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	validates :name, presence: true
  
  has_and_belongs_to_many :events
  
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sponsor }
      else
        format.html { render action: 'new' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:name, :url, :logo)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/_sponsors_events.html.erb
<table border="2">
  <thead>
    <tr>
      <td>Name</td>
      <td>start date</td>
      <td>end date</td>
    </tr>
  </thead>
  <tbody>
    
<% @sponsor.events.each do |s|%>
<tr>
  <td><%= link_to(s.name, event_path(s.id)) %></td>
  <td><%= s.start_date %></td>
  <td><%= s.end_date %></td>
</tr>
  <% end %>
  
</tbody>
</table>

app/views/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<h1>Listing sponsors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Logo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= sponsor.name %></td>
        <td><%= sponsor.url %></td>
        <td><%= sponsor.logo %></td>
        <td><%= link_to 'Show', sponsor %></td>
        <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
        <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/new.html.erb
<h1>New sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sponsor.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @sponsor.url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @sponsor.logo %>
</p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>

<% content_for :sidebar do %>

<%= render(partial: "sponsors_events", object: @sponsor)%>

<% end %>